name: Build Vector Store Images

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      VECTOR_VERSION:
        description: 'Git tag to build from'
        required: true

jobs:
  build-cloud-images:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.0.0
        with:
          version: '1.10.0'

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VECTOR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VECTOR_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup GCP credentials
        uses: google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: ${{ secrets.VECTOR_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.VECTOR_GCP_SERVICE_ACCOUNT }}

      - name: Determine Vector Store version
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            echo "VECTOR_VERSION=${{ github.event.inputs.vector_version }}" >> $GITHUB_ENV
          elif ${{ github.event_name == 'release' }}; then
            echo "VECTOR_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "Missing Vector Store version - Workflow cannot continue"
            exit 1
          fi

      - name: Build Images
        run: |
          packer plugins install github.com/hashicorp/googlecompute
          packer plugins install github.com/hashicorp/amazon
          echo GCP keys are missing: packer build -var vector_version="$VECTOR_VERSION" vector-store-template.json
          packer build -only=amazon-ebs -var vector_version="$VECTOR_VERSION" vector-store-template.json
          packer build -only=amazon-ebs -var vector_version="$VECTOR_VERSION" -var 'arch=arm64' vector-store-template.json
        working-directory: packer

      - name: Archive Packer manifest
        uses: actions/upload-artifact@v4
        with:
          name: vector-store-cloud-images-${{ env.VECTOR_VERSION }}
          path: packer/packer-manifest.json

      - name: Upload Packer manifest to the release
        if: github.event_name == 'release' && github.event.release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: packer/packer-manifest.json
          asset_name: vector-store-cloud-images-${{ env.VECTOR_VERSION }}.json
          asset_content_type: application/json
